services:
  # auth-service:
  #   build:
  #     context: ./auth-service
  #   container_name: auth-service
  #   depends_on:
  #     - auth-db
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - study-network

  #for replicas testing
  auth-service:
    build:
      context: ./auth-service
    depends_on:
      - auth-db
    ports:
      - "5000"
    networks:
      - study-network
    deploy:
      replicas: 3
    environment:
      - SERVICE_NAME=auth-service

  auth-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authdb
    volumes:
      - ./auth-db/init-auth.sql:/docker-entrypoint-initdb.d/init-auth.sql
    ports:
      - "5432:5432"
    networks:
      - study-network

  # websocket testing
  # flashcards-service:
  #   build:
  #     context: ./flashcards-service
  #   container_name: flashcards-service
  #   depends_on:
  #     - flashcards-db
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - study-network

  # for replicas testing
  flashcards-service:
    build:
      context: ./flashcards-service
    depends_on:
      - flashcards-db
    ports:
      - "5001"
    networks:
      - study-network
    deploy:
      replicas: 3
    environment:
      - SERVICE_NAME=flashcards-service

  flashcards-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashcardsdb
    ports:
      - "5433:5432"
    volumes:
      - ./flashcards-db/init-flash.sql:/docker-entrypoint-initdb.d/init-flash.sql
    networks:
      - study-network

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - flashcards-service
    networks:
      - study-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - study-network

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - study-network

networks:
  study-network:
    driver: bridge
