global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:5000"]

  - job_name: "flashcards-service"
    static_configs:
      - targets: ["flashcards-service:5001"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8080"]
